// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SustainabilityCanvas.Api.Data;

#nullable disable

namespace sustainability_canvas_api.Migrations
{
    [DbContext(typeof(SustainabilityCanvasContext))]
    [Migration("20251126150028_RemoveUsernameAndRoleChanges")]
    partial class RemoveUsernameAndRoleChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Impact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Relation")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Impacts");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.ImpactSdg", b =>
                {
                    b.Property<int>("ImpactId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<int>("SdgId")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.HasKey("ImpactId", "SdgId");

                    b.HasIndex("SdgId");

                    b.ToTable("ImpactSdgs");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.ProjectCollaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectCollaborators");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Sdg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Sdgs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "No Poverty"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Zero Hunger"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Good Health and Well-being"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Quality Education"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Gender Equality"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Clean Water and Sanitation"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Affordable and Clean Energy"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Decent Work and Economic Growth"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Industry, Innovation and Infrastructure"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Reduced Inequality"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Sustainable Cities and Communities"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Responsible Consumption and Production"
                        },
                        new
                        {
                            Id = 13,
                            Title = "Climate Action"
                        },
                        new
                        {
                            Id = 14,
                            Title = "Life Below Water"
                        },
                        new
                        {
                            Id = 15,
                            Title = "Life on Land"
                        },
                        new
                        {
                            Id = 16,
                            Title = "Peace, Justice and Strong Institutions"
                        },
                        new
                        {
                            Id = 17,
                            Title = "Partnerships for the Goals"
                        });
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Impact", b =>
                {
                    b.HasOne("SustainabilityCanvas.Api.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.ImpactSdg", b =>
                {
                    b.HasOne("SustainabilityCanvas.Api.Models.Impact", "Impact")
                        .WithMany("ImpactSdgs")
                        .HasForeignKey("ImpactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustainabilityCanvas.Api.Models.Sdg", "Sdg")
                        .WithMany()
                        .HasForeignKey("SdgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Impact");

                    b.Navigation("Sdg");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Profile", b =>
                {
                    b.HasOne("SustainabilityCanvas.Api.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SustainabilityCanvas.Api.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Project", b =>
                {
                    b.HasOne("SustainabilityCanvas.Api.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.ProjectCollaborator", b =>
                {
                    b.HasOne("SustainabilityCanvas.Api.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SustainabilityCanvas.Api.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.Impact", b =>
                {
                    b.Navigation("ImpactSdgs");
                });

            modelBuilder.Entity("SustainabilityCanvas.Api.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
